import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Web3ModalProvider } from '@/context/Web3Modal';
import { Toaster } from 'sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Toaster
          position="bottom-right"
          toastOptions={{
            classNames: {
              toast: '!bg-neutral-900 !border-neutral-800 !text-white font-mono rounded-lg shadow-xl',
              description: '!text-neutral-400 text-xs',
              error: '!border-red-500/40 !text-red-400',
              success: '!border-emerald-500/40 !text-emerald-400',
              info: '!border-blue-500/40 !text-blue-400',
            },
          }}
        />
        <Web3ModalProvider>
          {children}
        </Web3ModalProvider>
      </body>
    </html>
  );
}
