[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
test = "contracts/test"
script = "contracts/script"


auto_detect_remappings = false

via_ir = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options